services:
  sample-book-app-dev:
    build: .
    image: radud1337/sample-book-app
    container_name: sample-book-app-dev
    ports:
      - 1010:1050
    networks:
      - sample-book-app-compose-network
  sample-book-app-stg:
    build: .
    image: radud1337/sample-book-app
    container_name: sample-book-app-stg
    ports:
      - 2020:1050
    networks:
      - sample-book-app-compose-network
  sample-book-app-prod:
    build: .
    image: radud1337/sample-book-app
    container_name: sample-book-app-prod
    ports:
      - 3030:1050
    networks:
      - sample-book-app-compose-network

networks:
  sample-book-app-compose-network:
    name: sample-book-app-compose-network
